spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}  # 앱 비밀번호 16자리
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  scheduling:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret:
    key:  ${JWT_SECRET_KEY}

toss:
  secret-key:  ${TOSS_SECRET_KEY}

fedex:
  api:
    url:  ${FEDEX_API_URL}