spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret:
    key:  ${JWT_SECRET_KEY}

toss:
  secret-key:  ${TOSS_SECRET_KEY}

fedex:
  api:
    url:  ${FEDEX_API_URL}