package org.example.oshipserver.domain.order.entity.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CountryCode {
    GH("Ghana"),
    GA("Gabon"),
    GY("Guyana"),
    GM("Gambia"),
    GG("Guernsey"),
    GP("Guadeloupe"),
    GT("Guatemala"),
    GU("Guam"),
    GD("Grenada"),
    GR("Greece"),
    GL("Greenland"),
    GN("Guinea"),
    GW("Guinea-Bissau"),
    NA("Namibia"),
    NR("Nauru"),
    NG("Nigeria"),
    AQ("Antarctica"),
    SS("Republic Of South Sudan"),
    ZA("South Africa"),
    NL("Netherlands"),
    AN("Netherlands Antilles"),
    NP("Nepal"),
    NO("Norway"),
    NF("Norfolk Island"),
    NC("New Caledonia"),
    NZ("New Zealand"),
    NU("Niue"),
    NE("Niger"),
    NI("Nicaragua"),
    KR("Korea, Republic Of"),
    DK("Denmark"),
    DO("Dominican Republic"),
    DM("Dominica"),
    DE("Germany"),
    TL("East Timor"),
    LA("Lao People'S Democratic Republic"),
    LR("Liberia"),
    LV("Latvia"),
    RU("Russian Federation"),
    LB("Lebanon"),
    LS("Lesotho"),
    RE("Reunion"),
    RO("Romania"),
    LU("Luxembourg"),
    RW("Rwanda"),
    LY("Libyan Arab Jamahiriya"),
    LT("Lithuania"),
    LI("Liechtenstein"),
    MG("Madagascar"),
    MQ("Martinique"),
    MH("Marshall Islands"),
    YT("Mayotte"),
    MO("Macau"),
    MK("Republic Of Macedonia"),
    MW("Malawi"),
    MY("Malaysia"),
    ML("Mali"),
    IM("Isle Of Man"),
    MX("Mexico"),
    MC("Monaco"),
    MA("Morocco"),
    MU("Mauritius"),
    MR("Mauritania"),
    MZ("Mozambique"),
    ME("Montenegro"),
    MS("Montserrat"),
    MD("Moldova, Republic Of"),
    MV("Maldives"),
    MT("Malta"),
    MN("Mongolia"),
    US("United States"),
    UM("United States Minor Outlying Islands"),
    VI("Virgin Islands, U.S."),
    MM("Myanmar"),
    FM("Micronesia"),
    VU("Vanuatu"),
    BH("Bahrain"),
    BB("Barbados"),
    VA("Vatican City State"),
    BS("Bahamas"),
    BD("Bangladesh"),
    BM("Bermuda"),
    BJ("Benin"),
    VE("Venezuela"),
    VN("Viet Nam"),
    BE("Belgium"),
    BY("Belarus"),
    BZ("Belize"),
    BQ("Eilandgebied Bonaire"),
    BA("Bosnia Hercegovina"),
    BW("Botswana"),
    BO("Bolivia"),
    BI("Burundi"),
    BF("Burkina Faso"),
    BV("Bouvet Island"),
    BT("Bhutan"),
    MP("Northern Mariana Islands"),
    BG("Bulgaria"),
    BR("Brazil"),
    BN("Brunei Darussalam"),
    WS("Samoa"),
    SA("Saudi Arabia"),
    GS("South Georgia And The South Sandwich Islands"),
    SM("San Marino"),
    ST("Sao Tome And Principe"),
    MF("Saint-Martin"),
    BL("Saint Barthélemy"),
    PM("St. Pierre And Miquelon"),
    EH("Western Sahara"),
    SN("Senegal"),
    RS("Serbia"),
    SC("Seychelles"),
    LC("Saint Lucia"),
    VC("Saint Vincent And The Grenadines"),
    KN("Saint Kitts And Nevis"),
    SH("St. Helena"),
    SO("Somalia"),
    SB("Solomon Islands"),
    SD("Sudan"),
    SR("Suriname"),
    LK("Sri Lanka"),
    SJ("Svalbard And Jan Mayen Islands"),
    SE("Swaziland"),
    CH("Sweden"),
    ES("Switzerland"),
    SK("Spain"),
    SI("Slovakia"),
    SY("Slovenia"),
    SL("Syrian Arab Republic"),
    SX("Sierra Leone"),
    SG("Singapore"),
    AE("United Arab Emirates"),
    AW("Aruba"),
    AM("Armenia"),
    AR("Argentina"),
    AS("American Samoa"),
    IS("Iceland"),
    HT("Haiti"),
    IE("Ireland"),
    AZ("Azerbaijan"),
    AF("Afghanistan"),
    AD("Andorra"),
    AL("Albania"),
    DZ("Algeria"),
    AO("Angola"),
    AG("Antigua And Barbuda"),
    AI("Anguilla"),
    ER("Eritrea"),
    SZ("Eswatini"),
    EE("Estonia"),
    EC("Ecuador"),
    ET("Ethiopia"),
    SV("El Salvador"),
    GB("United Kingdom"),
    VG("Virgin Islands, British"),
    IO("British Indian Ocean Territory"),
    YE("Yemen, Republic Of"),
    OM("Oman"),
    AU("Australia"),
    AT("Austria"),
    HN("Honduras"),
    AX("Aland Islands"),
    WF("Wallis And Futuna Islands"),
    JO("Jordan"),
    UG("Uganda"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    UA("Ukraine"),
    IQ("Iraq"),
    IR("Iran"),
    IL("Israel"),
    EG("Egypt"),
    IT("Italy"),
    IN("India"),
    ID("Indonesia"),
    JP("Japan"),
    JM("Jamaica"),
    ZM("Zambia"),
    JE("Jersey"),
    GQ("Equatorial Guinea"),
    KP("Korea, Democratic People'S Republic Of"),
    GE("Georgia"),
    CN("China"),
    CF("Central African Republic"),
    DJ("Djibouti"),
    GI("Gibraltar"),
    ZW("Zimbabwe"),
    TD("Chad"),
    CZ("Czech Republic"),
    CL("Chile"),
    CM("Cameroon"),
    CV("Cape Verde"),
    KZ("Kazakhstan"),
    QA("Qatar"),
    KH("Cambodia"),
    CA("Canada"),
    KE("Kenya"),
    KY("Cayman Islands"),
    KM("Comoros"),
    CR("Costa Rica"),
    CC("Cocos Islands"),
    CI("Cote D'Ivoire"),
    CO("Colombia"),
    CG("Congo"),
    CD("Democratic Republic Of The Congo"),
    CU("Cuba"),
    KW("Kuwait"),
    CK("Cook Islands"),
    CW("Country Of Curaçao"),
    HR("Croatia"),
    CX("Christmas Island"),
    KG("Kyrgyzstan"),
    KI("Kiribati"),
    CY("Cyprus"),
    TW("Republic Of China (Taiwan)"),
    TJ("Tajikistan"),
    TZ("Tanzania, United Republic Of"),
    TH("Thailand"),
    TC("Turks And Caicos Islands"),
    TR("Turkey"),
    TG("Togo"),
    TK("Tokelau"),
    TO("Tonga"),
    TM("Turkmenistan"),
    TV("Tuvalu"),
    TN("Tunisia"),
    TT("Trinidad And Tobago"),
    PA("Panama"),
    PY("Paraguay"),
    PK("Pakistan"),
    PG("Papua New Guinea"),
    PW("Palau"),
    PS("Palestine"),
    FO("Faroe Islands"),
    PE("Peru"),
    PT("Portugal"),
    FK("Falkland Islands"),
    PL("Poland"),
    PR("Puerto Rico"),
    FR("France"),
    GF("French Guiana"),
    TF("French Southern Territories"),
    PF("French Polynesia"),
    FJ("Fiji"),
    FI("Finland"),
    PH("Philippines"),
    PN("Pitcairn"),
    HM("Heard And Mc Donald Islands"),
    HU("Hungary"),
    HK("Hong Kong");

    private final String englishName;
    }